apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: springapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
